// rankingMedals/index.js

const rankingMedals = {
  recruit: require("./Recruit.png"),
  apprentice: require("./Apprentice.png"),
  apprentice_G2: require("./Apprentice_G2.png"),
  brigadier: require("./Brigadier.png"),
  brigadier_G2: require("./Brigadier_G2.png"),
  brigadier_G3: require("./Brigadier_G3.png"),
  brigadier_G4: require("./Brigadier_G4.png"),
  captain: require("./Captain.png"),
  captain_G2: require("./Captain_G2.png"),
  captain_G3: require("./Captain_G3.png"),
  captain_G4: require("./Captain_G4.png"),
  colonel: require("./Colonel.png"),
  colonel_G2: require("./Colonel_G2.png"),
  colonel_G3: require("./Colonel_G3.png"),
  colonel_G4: require("./Colonel_G4.png"),
  commander: require("./Commander.png"),
  commander_G2: require("./Commander_G2.png"),
  commander_G3: require("./Commander_G3.png"),
  commander_G4: require("./Commander_G4.png"),
  corporal: require("./Corporal.png"),
  corporal_G2: require("./Corporal_G2.png"),
  general: require("./General.png"),
  general_G2: require("./General_G2.png"),
  general_G3: require("./General_G3.png"),
  general_G4: require("./General_G4.png"),
  gunnerySergeant: require("./GunnerySergeant.png"),
  gunnerySergeant_G2: require("./GunnerySergeant_G2.png"),
  gunnerySergeant_G3: require("./GunnerySergeant_G3.png"),
  gunnerySergeant_G4: require("./GunnerySergeant_G4.png"),
  lieutenant: require("./Lieutenant.png"),
  lieutenant_G2: require("./Lieutenant_G2.png"),
  lieutenant_G3: require("./Lieutenant_G3.png"),
  lieutenant_G4: require("./Lieutenant_G4.png"),
  major: require("./Major.png"),
  major_G2: require("./Major_G2.png"),
  major_G3: require("./Major_G3.png"),
  major_G4: require("./Major_G4.png"),
  private: require("./Private.png"),
  private_G2: require("./Private_G2.png"),
  sergeant: require("./Sergeant.png"),
  sergeant_G2: require("./Sergeant_G2.png"),
  sergeant_G3: require("./Sergeant_G3.png"),
};

export default rankingMedals;
